name = "daggerbrain-feedback"
main = "src/index.ts"
compatibility_date = "2026-03-18"

[[d1_databases]]
binding = "DB"
database_name = "daggerbrain_feedback"
database_id = "1f02c7f2-dc5a-40f7-80c7-fea59f004b49"
migrations_dir = "migrations"

[observability]
enabled = true

[observability.logs]
invocation_logs = true
head_sampling_rate = 1
